[tool.poetry]
name = "libiancrawlers"
version = "0.1.0"
description = "Fxxxxxking crawlers"
authors = ["Your Name <you@example.com>"]
license = "fuck"

[tool.poetry.dependencies]
python = "~3.9"
curl-cffi = "^0.7.3"
loguru = "^0.7.2"
fire = "^0.7.0"
confection = "^0.1.5"
json5 = "^0.9.28"
random-user-agent = "^1.0.1"
psycopg2-binary = "^2.9.10"

[tool.poetry.dev-dependencies]

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest-randomly = "^3.15.0"
pytest = "^8.2.0"

[tool.poetry.group.crawler-xiaohongshu]
optional = true

[tool.poetry.group.crawler-xiaohongshu.dependencies]
xhs = "^0.2.13"

[tool.poetry.scripts]
xiaohongshu-search = "libiancrawlers.xiaohongshu.search:cli"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
